
# --- Item Names ---

lightingAxe: "#4390ff!Lighting Axe"
healingSword: "#ffdc8c!Healing Axe"
idolsIncarnate: "#fe4448!Idols Incarnate"
terminator: "#c545ff!Terminator"
frozenWand: "#74dfff!Frozen Wand"
impulseSword: "#d3d3d3!Impulse Sword"
amberScythe: "#ffb959!Amber Scythe"
milkPotion: "#cfcfcf!Milk Potion"
giantSword: "#ffd4d4!Giant Sword"
furiousAxe: "#53227d!Furious Axe"
airBurner: "#ff8d00!Air Burner"
runicDaggerFrozen: "#6afff9!Runic Dagger"
runicDaggerMolten: "#ea5d00!Runic Dagger"
mythicSwordOfLegends: "#f97aff!Mythic Sword of Legends"
flamingWhip: "#ed794c!Flaming Whip"
darknessConcentrator: "#5e197d!Darkness Concentrator"
infectedSword: "#114e19!Infected Sword"
swordOfGrowth: "#009209!Sword Of Growth"
singularity: "#44007e!Singularity"
corruptedMythicIdolIncarnate: "#4a008e!Corrupted Mythic Idol Incarnate"

# --- Item Settings

frozenWandRadius: 7
impulseSwordRadius: 15
airBurnerRadius: 10
terminatorAbilityRange: 15

# --- Item Cooldown ---

impulseSwordCooldown: 5
lightningAxeCooldown: 3
frozenWandCooldown: 7
amberScytheCooldown: 7
giantSwordCooldown: 15
furiousAxeCooldown: 1
terminatorCooldown: 1
airBurnerCooldown: 7
mythicSwordOfLegendsCooldown: 15
flamingWhipCooldown: 1
darknessConcentratorCooldown: 2

# --- Mobs Nametags ---

WitherSpiderNametag: "#5f5f5f!Wither Spider"
ParasiteNametag: "#1a590a!Parasite"
InfectedZombieNametag: "#2cb70b!Infected Zombie"
MasterAssassinNametag: "#5a3d6d!Master Assassin"
AirSpiritNametag: "#dfdfdf!Ethereal Spirit"
FireSpiritNametag: "#ff8e66!Flaming Spirit"
IceSpiritNametag: "#74dfff!Frozen Spirit"
SemiIdolNametag: "#0ab7ff!Semi Idol"
AncientZombieNametag: "#5b5b5b!Ancient Zombie"
OverworldInvaderNamtetag: "#ff7829!Overworld Invader"
GhostNametag: "#082759!Ghost"
PhantomRiderNametag: "#2b0089!Phantom Rider"
FrozenSoulNametag: "#1283fc!Frozen Soul"
DesertGuardianNametag: "#b3743d!Desert Guardian"
RevenantArcherNametag: "#5e218f!Revenant Archer"
MushroomMonsterNametag: "#630606!Mushroom Monster"
CyclopsNametag: "#9191a5!Cyclops"
WatchingEyeNametag: "#28538d!Watching Eye"

MiniBossPrefix: "#ff535c!MINI BOSS " # --- Miniboss prefix
BossPrefix: "#7d2222!BOSS " # --- Boss prefix

# --- Mobs HP ---

WitherSpiderHealth: 40
ParasiteHealth: 150
InfectedZombieHealth: 30
MasterAssassinHealth: 25
AirSpiritHealth: 30
FireSpiritHealth: 30
IceSpiritHealth: 30
SemiIdolHealth: 200
AncientZombieHealth: 30
OverworldInvaderHealth: 125
GhostHealth: 50
PhantomRiderHealth: 30
FrozenSoulHealth: 90
DesertGuardianHealth: 30
RevenantArcherHealth: 125
MushroomMonsterHealth: 100
CyclopsHealth: 145
WatchingEyeHealth: 20

# --- Mob Drops ---

AmberShardName: "#ff9402!Amber Shard"
ImpulseShardName: "#a485ff!Impulse Shard"
FrozenShardName: "#74dfff!Frozen Shard"
InfectedFleshName: "#006d04!Infected Flesh"
InfectedHeartName: "#6e0019!Infected Heart"
ParasiteHeartName: "#25d929!Parasite Heart"
LightningShardName: "#88aedf!Lightning Shard"
WitheredEyeName: "#434343!Withered Eye"
AncientShardName: "#5b5b5b!Ancient Shard"
DecayedHeartName: "#242331!Decayed Heart"
WitheredShardName: "#443439!Withered Shard"
NetherCatalystName: "#8a8a8a!Nether Catalyst"
NetherEssenceName: "#e35f17!Nether Essence"
CursedCrownName: "#d6a20d!Cursed Crown"
CursedHeartName: "#630f0f!Cursed Heart"
CursedBoneName: "#615959!Cursed Bone"
DestructiveShard: "#ff0000!Destructive Shard"
GhostEssence: "#a3b5b8!Ghost Essence"
ShadyAura: "#aba3b8!Shady Aura"

# --- Mob Drop Lore ---

CommonRarity: "#c3c3c3!Common Drop"
RareRarity: "#5a6eff!Rare Drop"
EpicRarity: "#5c00ac!Epic Drop"
LegendaryRarity: "#ff9e29!Legendary Drop"
MythicRarity: "#ff3e3e!Mythic Drop"
DivineRarity: "#ff96f5!Divine Drop"

# --- Mob Drop Chance ---

CommonChance: 80
RareChance: 30
EpicChance: 10
LegendaryChance: 5
MythicChance: 3
DivineChance: 1

# --- Recipes ---

EnableTerminatorRecipe: 1
EnableMilkPotionRecipe: 1
EnableLightningAxeRecipe: 1
EnableImpulseSwordRecipe: 1
EnableIdolsIncarnateRecipe: 1
EnableHealingSwordRecipe: 1
EnableGiantSwordRecipe: 1
EnableFuriousRecipe: 1
EnableFrozenWandRecipe: 1
EnableAmberScytheRecipe: 1
EnableAirBurnerRecipe: 1
EnableRunicSwordRecipe: 1
FlamingWhipRecipe: 1
MythicSwordOfLegendsRecipe: 1
DarknessConcentratorRecipe: 1
InfectedSwordRecipe: 1

# --- Scrolls Names

ArrowStormName: "#d47dff!Arrow Storm Scroll"
NetherStormScroll: "#460000!Nether Storm Scroll"
HealingTotemScroll: "#ffff69!Healing Totem Scroll"
InfernalAuraScroll: "#a11900!Infernal Aura Scroll"
FrozenStormScroll: "#065363!Frozen Storm Scroll"


# --- Bosses ---

#Witherus Netherlord
NetherLordBossNametag: "#d60e00!Witherus Netherlord"
NetherLordBossHealth: 500
NetherHealerNametag: "#f56138!Infernal totem of healing"
NetherHealerHealth: 20

#Cursed Emperor
CursedEmperorBossNametag: "#75b7a4!Cursed Emperor"
CursedEmperorBossHealth: 650
RatNametag: "#425f6f!Rat"
RatHealth: 7
LegionaryNametag: "#3c5664!Emperor's Legionary"
LegionaryHealth: 20
AncientPriestName: "#873eed!Ancient Priest"
AncientPriestHealth: 40


# --- MegaBossess ---

#Giant
GiantNametag: "#e83838!Giant"
GiantHealth: 2000

# --- Armor sets ---

#Grandmaster Armorset

GrandmasterBootsName: "#ffc455!Grandmaster's Boots"
GrandmasterLeggingsName: "#ffc455!Grandmaster's Leggings"
GrandmasterChestplateName: "#ffc455!Grandmaster's Chestplate"
GrandmasterHelmetName: "#ffc455!Grandmaster's Helmet"

#Master Assassin Armorset

MasterAssassinBootsName: "#260047!Master Assassin Boots"
MasterAssassinLeggingsName: "#260047!Master Assassin Leggings"
MasterAssassinChestplateName: "#00056b!Master Assassin Chestplate"

MasterAssassinArmorCooldown: 5

#Frozen Warrior Armorset

FrozenWarriorBootsName: "#619dff!Frozen Warrior Boots"
FrozenWarriorLeggingsName: "#619dff!Frozen Warrior Leggings"
FrozenWarriorChestplateName: "#619dff!Frozen Warrior Chestplate"
FrozenWarriorHelmetName: "#619dff!Frozen Warrior Helmet"

#Mythic Warrior Armorset

MythicWarriorBootsName: "#f97aff!Mythic Warrior Boots"
MythicWarriorLeggingsName: "#f97aff!Mythic Warrior Leggings"
MythicWarriorChestplateName: "#f97aff!Mythic Warrior Chestplate"
MythicWarriorHelmetName: "#f97aff!Mythic Warrior Helmet"

#Thief Armorset

ThiefBootsName: "#28272b!Thief's Boots"
ThiefLeggingsName: "#28272b!Thief's Pants"
ThiefChestplateName: "#28272b!Thief's Coat"
ThiefHelmetName: "#28272b!Thief's Hood"

#Beast Armorset

BeastChestplateName: "#d6d6d6!Chestplate of the Beast"
BeastHelmetName: "#d6d6d6!Helmet of the Beast"

#Corrupted Mythic Warrior Armorset

CorruptedMythicWarriorBootsName: "#622aa3!Corrupted Mythic Warrior Boots"
CorruptedMythicWarriorLeggingsName: "#622aa3!Corrupted Mythic Warrior Leggings"
CorruptedMythicWarriorChestplateName: "#622aa3!Corrupted Mythic Warrior Chestplate"
CorruptedMythicWarriorHelmetName: "#622aa3!Corrupted Mythic Warrior Helmet"

#Glacial Mythic Warrior Armorset

GlacialMythicWarriorBootsName: "#73e5ff!Glacial Mythic Warrior Boots"
GlacialMythicWarriorLeggingsName: "#73e5ff!Glacial Mythic Warrior Leggings"
GlacialMythicWarriorChestplateName: "#73e5ff!Glacial Mythic Warrior Chestplate"
GlacialMythicWarriorHelmetName: "#73e5ff!Glacial Mythic Warrior Helmet"

# Natural Spawn
SpawnWitherSpiders: 1
SpawnInfectedZombies: 1
SpawnParasite: 1
SpawnMasterAssassins: 1
SpawnAncientZombies: 1
SpawnSemiIdols: 1
SpawnOverworldInvaders: 1
SpawnGhosts: 1
SpawnPhantomRiders: 1
SpawnDesertGuardians: 1