lightingAxe: "§9Lighting Axe"
healingSword: "§6Healing Axe"
idolsIncarnate: "§cIdols Incarnate"
terminator: "§dTerminator"
destructiveBow: "§cDestructive Bow"
terminatorAbilityRange: 15
healingSwordCooldown: 3