
# --- Item Names ---

lightingAxe: "#4390ff!Lighting Axe"
healingSword: "#ffdc8c!Healing Axe"
idolsIncarnate: "#fe4448!Idols Incarnate"
terminator: "#c545ff!Terminator"
frozenWand: "#74dfff!Frozen Wand"
impulseSword: "#d3d3d3!Impulse Sword"
amberScythe: "#ffb959!Amber Scythe"
milkPotion: "#cfcfcf!Milk Potion"
giantSword: "#ffd4d4!Giant Sword"
furiousAxe: "#53227d!Furious Axe"
airBurner: "#ff8d00!Air Burner"

# --- Item Cooldown ---

frozenWandRadius: 7
impulseSwordRadius: 15
impulseSwordCooldown: 5
terminatorAbilityRange: 15
lightningAxeCooldown: 3
frozenWandCooldown: 7
amberScytheCooldown: 7
giantSwordCooldown: 15
furiousAxeCooldown: 1

# --- Mobs Nametags ---

WitherSpiderNametag: "#5f5f5f!Wither Spider"
ParasiteNametag: "#1a590a!Parasite"
InfectedZombieNametag: "#2cb70b!Infected Zombie"
MasterAssassinNametag: "#5a3d6d!Master Assassin"
AirSpiritNametag: "#dfdfdf!Ethereal Spirit"
FireSpiritNametag: "#ff8e66!Flaming Spirit"
IceSpiritNametag: "#74dfff!Frozen Spirit"

MiniBossPrefix: "#ff535c!MINI BOSS " # --- Miniboss prefix
BossPrefix: "#7d2222!BOSS " # --- Boss prefix

# --- Mobs HP ---

WitherSpiderHealth: 40
ParasiteHealth: 50
InfectedZombieHealth: 30
MasterAssassinHealth: 25
AirSpiritHealth: 30
FireSpiritHealth: 30
IceSpiritHealth: 30