lightingAxe: "§9Lighting Axe"
healingSword: "§6Healing Axe"
idolsIncarnate: "§cIdols Incarnate"
terminator: "§dTerminator"
frozenWand: "§bFrozen Wand"
impulseSword: "§eImpulse Sword"
amberScythe: "§6Amber Scythe"
milkPotionName: "§aMilk Potion"
frozenWandRadius: 7
impulseSwordRadius: 15
impulseSwordCooldown: 5
terminatorAbilityRange: 15
lightningAxeCooldown: 3
frozenWandCooldown: 7
amberScytheCooldown: 7
WitherSpiderNametag: "#5f5f5f!Wither Spider"
ParasiteNametag: "#1a590a!Parasite"
InfectedZombieNametag: "#2cb70b!Infected Zombie"
MasterAssassinNametag: "#5a3d6d!Master Assassin"
MiniBossPrefix: "#ff535c!MINI BOSS "
WitherSpiderHealth: 40
ParasiteHealth: 50
InfectedZombieHealth: 30
MasterAssassinHealth: 25
showCustomNametags: true