
# --- Item Names ---

lightingAxe: "#4390ff!Lighting Axe"
healingSword: "#ffdc8c!Healing Axe"
idolsIncarnate: "#fe4448!Idols Incarnate"
terminator: "#c545ff!Terminator"
frozenWand: "#74dfff!Frozen Wand"
impulseSword: "#d3d3d3!Impulse Sword"
amberScythe: "#ffb959!Amber Scythe"
milkPotion: "#cfcfcf!Milk Potion"
giantSword: "#ffd4d4!Giant Sword"
furiousAxe: "#53227d!Furious Axe"
airBurner: "#ff8d00!Air Burner"

# --- Item Settings

frozenWandRadius: 7
impulseSwordRadius: 15
airBurnerRadius: 10

# --- Item Cooldown ---

impulseSwordCooldown: 5
terminatorAbilityRange: 15
lightningAxeCooldown: 3
frozenWandCooldown: 7
amberScytheCooldown: 7
giantSwordCooldown: 15
furiousAxeCooldown: 1
terminatorCooldown: 1
airBurnerCooldown: 7

# --- Mobs Nametags ---

WitherSpiderNametag: "#5f5f5f!Wither Spider"
ParasiteNametag: "#1a590a!Parasite"
InfectedZombieNametag: "#2cb70b!Infected Zombie"
MasterAssassinNametag: "#5a3d6d!Master Assassin"
AirSpiritNametag: "#dfdfdf!Ethereal Spirit"
FireSpiritNametag: "#ff8e66!Flaming Spirit"
IceSpiritNametag: "#74dfff!Frozen Spirit"
SemiIdolNametag: "#0ab7ff!Semi Idol"
AncientZombieNametag: "#5b5b5b!Ancient Zombie"
OverworldInvaderNamtetag: "#ff7829!Overworld Invader"

MiniBossPrefix: "#ff535c!MINI BOSS " # --- Miniboss prefix
BossPrefix: "#7d2222!BOSS " # --- Boss prefix

# --- Mobs HP ---

WitherSpiderHealth: 40
ParasiteHealth: 150
InfectedZombieHealth: 30
MasterAssassinHealth: 25
AirSpiritHealth: 30
FireSpiritHealth: 30
IceSpiritHealth: 30
SemiIdolHealth: 200
AncientZombieHealth: 30


# --- Mob Drops ---

AmberShardName: "#ff9402!Amber Shard"
ImpulseShardName: "#a485ff!Impulse Shard"
FrozenShardName: "#74dfff!Frozen Shard"
InfectedFleshName: "#006d04!Infected Flesh"
InfectedHeartName: "#6e0019!Infected Heart"
ParasiteHeartName: "#25d929!Parasite Heart"
LightningShardName: "#88aedf!Lightning Shard"
WitheredEyeName: "#434343!Withered Eye"
AncientShardName: "#5b5b5b!Ancient Shard"
DecayedHeartName: "#242331!Decayed Heart"

# --- Mob Drop Lore ---

CommonRarity: "#c3c3c3!Common Drop"
RareRarity: "#5a6eff!Rare Drop"
EpicRarity: "#5c00ac!Epic Drop"
LegendaryRarity: "#ff9e29!Legendary Drop"
MythicRarity: "#ff3e3e!Mythic Drop"
DivineRarity: "#ff96f5!Divine Drop"

# --- Mob Drop Chance ---

CommonChance: 80
RareChance: 30
EpicChance: 10
LegendaryChance: 5
MythicChance: 3
DivineChance: 1

# --- Recipes ---

EnableTerminatorRecipe: 1
EnableMilkPotionRecipe: 1
EnableLightningAxeRecipe: 1
EnableImpulseSwordRecipe: 1
EnableIdolsIncarnateRecipe: 1
EnableHealingSwordRecipe: 1
EnableGiantSwordRecipe: 1
EnableFuriousRecipe: 1
EnableFrozenWandRecipe: 1
EnableAmberScytheRecipe: 1
EnableAirBurnerRecipe: 1

# --- Scrolls Names

ArrowStormName: "#d47dff!Arrow Storm Scroll"

# --- Bosses ---

#--Witherus Netherlord
NetherLordBossNametag: "#d60e00!Witherus Netherlord"
NetherLordBossHealth: 500
NetherHealerNametag: "#f56138!Infernal Totem of Eternal Healing"
NetherHealerHealth: 20
