lightingAxe: "§9Lighting Axe"
healingSword: "§6Healing Axe"
idolsIncarnate: "§cIdols Incarnate"
terminator: "§dTerminator"
frozenWand: "§bFrozen Wand"
frozenWandRadius: 7
terminatorAbilityRange: 15
lightningAxeCooldown: 3
frozenWandCooldown: 7
WitherSpiderNametag: "§8Wither Spider"
NecromancerNametag: "§9Necromancer"
InfectedZombieNametag: "§2Infected Zombie"
WitherSpiderHealth: 40
NecromancerHealth: 50
InfectedZombieHealth: 30
showCustomNametags: true